nnoremap ,rc :<C-u>Unite rails/controller<CR>
nnoremap ,rd :<C-u>Unite rails/db<CR>
nnoremap ,rh :<C-u>Unite rails/helper<CR>
nnoremap ,ri :<C-u>Unite rails/initializer<CR>
nnoremap ,rj :<C-u>Unite rails/javascript<CR>
nnoremap ,rm :<C-u>Unite rails/model<CR>
nnoremap ,rs :<C-u>Unite rails/stylesheet<CR>
nnoremap ,rt :<C-u>Unite rails/spec<CR>
nnoremap ,rv :<C-u>Unite rails/view<CR>
