nnoremap ,C :<C-u>Unite rails/controller<CR>
nnoremap ,D :<C-u>Unite rails/db<CR>
nnoremap ,H :<C-u>Unite rails/helper<CR>
nnoremap ,I :<C-u>Unite rails/initializer<CR>
nnoremap ,J :<C-u>Unite rails/javascript<CR>
nnoremap ,M :<C-u>Unite rails/model<CR>
nnoremap ,S :<C-u>Unite rails/stylesheet<CR>
nnoremap ,T :<C-u>Unite rails/spec<CR>
nnoremap ,V :<C-u>Unite rails/view<CR>
