include_cookbook 'dev_tools'
include_cookbook 'git'

include_cookbook 'anyenv'
include_cookbook 'fish'
include_cookbook 'jq'
include_cookbook 'golang'
include_cookbook 'tmux'
include_cookbook 'rbenv'
include_cookbook 'pyenv'
include_cookbook 'ndenv'
include_cookbook 'neovim'
include_cookbook 'mysql'
include_cookbook 'redis'
include_cookbook 'docker'
include_cookbook 'vagrant'
include_cookbook 'phantomjs'
