include_cookbook 'git'

include_cookbook 'anyenv'
include_cookbook 'ctags'
include_cookbook 'fish'
include_cookbook 'jq'
include_cookbook 'golang'
include_cookbook 'tmux'
include_cookbook 'rbenv'
include_cookbook 'pyenv'
include_cookbook 'nodenv'
include_cookbook 'mysql'
include_cookbook 'redis'
include_cookbook 'rust'
include_cookbook 'docker'
include_cookbook 'vagrant'
