# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"

  config.proxy.http     = ENV['http_proxy']  if ENV['http_proxy']
  config.proxy.https    = ENV['https_proxy'] if ENV['https_proxy']
  config.proxy.no_proxy = ENV['no_proxy']    if ENV['no_proxy']

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box_check_update = false
  config.vm.boot_timeout     = 300

  config.vm.network :forwarded_port, guest: 22, host: ENV.fetch('VAGRANT_SSH_PORT', 2222), id: 'ssh', auto_correct: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = ENV.fetch('VAGRANT_MEMORY', 2048)
    vb.cpus   = ENV.fetch('VAGRANT_CPUS',   2)
    vb.customize [
      'modifyvm',           :id,
      '--hwvirtex',         'on',
      '--nestedpaging',     'on',
      '--largepages',       'on',
      '--ioapic',           'on',
      '--pae',              'on',
      '--paravirtprovider', 'kvm',
    ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y git

    echo 'alias vim=vi' >> /home/vagrant/.bashrc
    echo 'git clone https://github.com/masa0x80/dotfiles.git $HOME/.dotfiles' > /home/vagrant/install
    echo 'cd $HOME/.dotfiles' >> /home/vagrant/install
    echo 'make deploy'        >> /home/vagrant/install
    echo 'make init'          >> /home/vagrant/install
    chown vagrant: /home/vagrant/install
  SHELL
end
