[tools]
aws-vault = "7.2.0"
deno = "1.40.0"
go = "1.22.0"
gradle = "8.6"
groovy = "4.0.18"
java = "corretto-21.0.1.12.1"
neovim = "0.9.5"
node = "21.6.2"
python = "3.12.2"
ruby = "3.3.0"
rust = "1.76.0"
sops = "3.8.1"
terraform = "1.7.3"
terraform-docs = "0.17.0"
