[tools]
# https://github.com/99designs/aws-vault/tags
aws-vault = "7.2.0"
# https://github.com/getsops/sops/tags
sops = "3.8.1"
# https://github.com/neovim/neovim/releases
neovim = "0.10.0"

# https://go.dev/dl/
go = "1.22.3"

# https://github.com/corretto/corretto-21/tags
java = "corretto-21.0.2.13.1"
# https://gradle.org/install/
gradle = "8.7"
# https://groovy.apache.org/download.html
groovy = "4.0.21"

# https://nodejs.org/en/download
node = "22.2.0"
# https://github.com/denoland/deno/tags
deno = "1.43.5"

# https://www.python.org/downloads/
python = "3.12.3"

# https://www.ruby-lang.org/en/downloads/releases/
ruby = "3.3.1"

# https://github.com/rust-lang/rust/tags
rust = "1.78.0"

# https://github.com/hashicorp/terraform/tags
terraform = "1.8.3"
# https://github.com/terraform-docs/terraform-docs/tags
terraform-docs = "0.17.0"

usage = "latest"
