include_cookbook 'global'
include_cookbook 'gibo'
include_cookbook 'imagemagick'
include_cookbook 'jo'
include_cookbook 'plenv'
include_cookbook 'postgresql'
include_cookbook 'rust'
include_cookbook 'vim'
