complete -c sec -d 'Pass command wrapper'
complete -c sec -n '__fish_use_subcommand' -a list -d 'List up files'
complete -c sec -n '__fish_use_subcommand' -a backup -d 'Backup the file'
complete -c sec -n '__fish_use_subcommand' -a show -d 'Print the file on the standard output'
complete -c sec -n '__fish_use_subcommand' -a restore -d 'Restore the file'
complete -c sec -n '__fish_use_subcommand' -a help -d 'Help'
