- name: uninstall previous version
  yum: name=git state=absent
  become: yes
- name: prepare to install git
  yum: name={{ item }} state=present
  with_items:
    - gcc-c++
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - perl-ExtUtils-MakeMaker
    - xmlto
    - asciidoc
  become: yes
- name: download git source file
  command: zsh -lc "curl -LO https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz" chdir={{ src_dir }}
- name: extract git source file
  unarchive: src={{ src_dir }}/git-{{ git_version }}.tar.gz dest={{ src_dir }} copy=no
- name: install git
  shell: ./configure --prefix=/usr/local && make && make install chdir={{ src_dir }}/git-{{ git_version }}
  become: yes
- name: install git man
  shell: make install-man chdir={{ src_dir }}/git-{{ git_version }}
  become: yes
