- name: uninstall previous version
  yum: name={{ item }} state=absent
  with_items:
    - libevent
    - libevent-devel
    - libevent-headers
  sudo: yes
- name: prepare to install libevent
  yum: name={{ item }} state=latest
  with_items:
    - gcc-c++
    - openssl
    - openssl-devel
  sudo: yes
- name: download libevent source file
  # comment out because of "error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure"
  # get_url: url=https://github.com/downloads/libevent/libevent/libevent-{{ libevent_version }}.tar.gz dest={{ src_dir }}/libevent-{{ libevent_version }}.tar.gz
  command: zsh -lc "curl -LO https://github.com/downloads/libevent/libevent/libevent-{{ libevent_version }}.tar.gz" chdir={{ src_dir }}
- name: extract libevent source file
  unarchive: src={{ src_dir }}/libevent-{{ libevent_version }}.tar.gz dest={{ src_dir }} copy=no
- name: install libevent
  shell: ./configure && make && make install chdir={{ src_dir }}/libevent-{{ libevent_version }}
  sudo: yes
- name: check libevent.conf
  shell: grep '^/usr/local/lib$' /etc/ld.so.conf.d/libevent.conf
  register: libevent_conf
  failed_when:  libevent_conf.rc not in [0, 1, 2]
  changed_when: libevent_conf.rc not in [0, 1, 2]
  sudo: yes
- name: set up libevent.conf
  shell: echo '/usr/local/lib' >> /etc/ld.so.conf.d/libevent.conf && ldconfig
  sudo: yes
  when: libevent_conf|failed
- name: set up symbolic link
  shell: ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5 creates=/usr/lib64/libevent-2.0.so.5
  sudo: yes
