- include: imagemagick.yml
- include: aws.yml

- name: check autojump
  shell: PATH=$PATH:{{ bin_dir }} type -a autojump
  register: autojump
  failed_when:  autojump.rc not in [0, 1]
  changed_when: autojump.rc not in [0, 1]
- include: autojump.yml
  when: autojump|failed

- name: check node version
  stat: path={{ home_dir }}/.anyenv/envs/ndenv
  register: ndenv_dir
- include: ndenv.yml
  when: ndenv_dir.stat.exists == False

- name: check git
  shell: PATH=$PATH:{{ bin_dir }} type -a git && git --version | grep {{ git_version }}
  register: git
  failed_when:  git.rc not in [0, 1]
  changed_when: git.rc not in [0, 1]
- include: git.yml
  when: git|failed
