- include: imagemagick.yml
  tags: imagemagick
- include: aws.yml
  tags: aws
- include: redis.yml
  tags: redis
- include: zplug.yml
  tags: zplug

- name: check vim
  shell: PATH=$PATH:{{ bin_dir }} type -a vim && vim --version | grep 'VIM - Vi IMproved {{ vim_version }}'
  register: vim
  failed_when:  vim.rc not in [0, 1]
  changed_when: vim.rc not in [0, 1]
  tags: vim
- include: vim.yml
  when: vim|failed
  tags: vim

- name: check libevent
  shell: ldconfig -p | grep '/usr/lib64/libevent-2.0.so.5'
  register: libevent
  failed_when:  libevent.rc not in [0, 1]
  changed_when: libevent.rc not in [0, 1]
  tags: libevent
- include: libevent.yml
  when: libevent|failed
  tags: libevent

- name: check tmux
  shell: PATH=$PATH:{{ bin_dir }} type -a tmux
  register: tmux
  failed_when:  tmux.rc not in [0, 1]
  changed_when: tmux.rc not in [0, 1]
  tags: tmux
- include: tmux.yml
  when: tmux|failed
  tags: tmux

- name: check node version
  stat: path={{ home_dir }}/.anyenv/envs/ndenv
  register: ndenv_dir
  tags: ndenv
- include: ndenv.yml
  when: ndenv_dir.stat.exists == False
  tags: ndenv

- name: check postgresql
  shell: PATH=$PATH:{{ bin_dir }} type -a postgres
  register: postgresql
  failed_when:  postgresql.rc not in [0, 1]
  changed_when: postgresql.rc not in [0, 1]
  tags: postgresql
- include: postgresql.yml
  when: postgresql|failed
  tags: postgresql

- name: check git
  shell: PATH=$PATH:{{ bin_dir }} type -a git && git --version | grep {{ git_version }}
  register: git
  failed_when:  git.rc not in [0, 1]
  changed_when: git.rc not in [0, 1]
  tags: git
- include: git.yml
  when: git|failed
  tags: git
