- include: imagemagick.yml
- include: aws.yml

- name: check git man
  shell: PATH=$PATH:{{ bin_dir }} man git
  register: git_man
  failed_when:  git_man.rc not in [0, 1]
  changed_when: git_man.rc not in [0, 1]
- include: git_man.yml
  when: git_man|failed

- name: check autojump
  shell: PATH=$PATH:{{ bin_dir }} type -a autojump
  register: autojump
  failed_when:  autojump.rc not in [0, 1]
  changed_when: autojump.rc not in [0, 1]
- include: autojump.yml
  when: autojump|failed

- name: check jq
  stat: path={{ bin_dir }}/jq
  register: jq
- include: jq.yml
  when: jq.stat.exists == False

- name: check node version
  stat: path={{ home_dir }}/.anyenv/envs/ndenv
  register: ndenv_dir
- include: ndenv.yml
  when: ndenv_dir.stat.exists == False
