- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    src_dir:  "{{ home_dir }}/src"
    bin_dir:  /usr/local/bin

    proxy_env:
      ftp_proxy: "{{ lookup('env', 'http_proxy') }}"

    node_version:     v5.0.0
  tasks:
    - include: tasks/imagemagick.yml
    - include: tasks/aws.yml

    - name: check autojump
      shell: PATH=$PATH:{{ bin_dir }} type -a autojump
      register: autojump
      failed_when:  autojump.rc not in [0, 1]
      changed_when: autojump.rc not in [0, 1]
    - include: tasks/autojump.yml
      when: autojump|failed

    - name: check jq
      stat: path={{ bin_dir }}/jq
      register: jq
    - include: tasks/jq.yml
      when: jq.stat.exists == False

    - name: check node version
      stat: path={{ home_dir }}/.anyenv/envs/ndenv
      register: ndenv_dir
    - include: tasks/ndenv.yml
      when: ndenv_dir.stat.exists == False

    - name: check mysql version
      shell: mysql --version | sed -e 's/.*Distrib \([0-9.]\+\), .\+/\1/'
      register: installed_mysql_version
    - name: check mysql
      shell: PATH=$PATH:{{ bin_dir }} type -a mysql
      register: mysql
      failed_when:  mysql.rc not in [0, 1]
      changed_when: mysql.rc not in [0, 1]
    - include: tasks/mysql.yml
      when: mysql|failed or installed_mysql_version.stdout | version_compare(mysql_version, '<')
