oh-my-fish/plugin-osx
oh-my-fish/plugin-cd
masa0x80/angler.fish
masa0x80/complete_ssh_host.fish
masa0x80/complete_mkr_host_ip.fish
masa0x80/git_add_keybind.fish
masa0x80/git_checkout_keybind.fish
masa0x80/ghq_cd_keybind.fish
masa0x80/filtering_history_keybind.fish
