vim.api.nvim_create_user_command("T", function()
	vim.fn.execute(":e " .. vim.fn.trim(vim.fn.system("scrapbook_path $(current_dir)/todo.md")))
end, {})
vim.api.nvim_create_user_command("Todo", function()
	vim.fn.execute(":e " .. vim.fn.trim(vim.fn.system("scrapbook_path $(current_dir)/todo.md")))
end, {})

vim.api.nvim_create_user_command("M", function()
	vim.fn.execute(":e " .. vim.fn.trim(vim.fn.system("scrapbook_path $(current_dir)/$(date +%Y-%m-%d).md")))
end, {})
vim.api.nvim_create_user_command("Memo", function()
	vim.fn.execute(":e " .. vim.fn.trim(vim.fn.system("scrapbook_path $(current_dir)/$(date +%Y-%m-%d).md")))
end, {})
