- name: prepare to install rbenv
  yum: name={{ item }} state=latest
  with_items:
    - gcc-c++
    - openssl-devel
    - readline-devel
    - libffi-devel
    - libxslt-devel
    - gecode-devel
  sudo: yes
- name: install rbenv
  shell: "{{ home_dir }}/.anyenv/bin//anyenv install rbenv"
- name: fix ruby version
  shell: "{{ home_dir }}/.anyenv/envs/rbenv/bin/rbenv install {{ ruby_version }}; {{ home_dir }}/.anyenv/envs/rbenv/bin/rbenv global {{ ruby_version }}"
- name: bundler
  shell: "{{ home_dir }}/.anyenv/envs/rbenv/bin/rbenv exec gem install bundler"
