# MEMO: This file is based on https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh

# Aliases

alias g git

alias ga   'git add'
alias gaa  'git add --all'
alias gapa 'git add --patch'

alias gb   'git branch'
alias gba  'git branch -a'
alias gbl  'git blame -b -w'
alias gbnm 'git branch --no-merged'
alias gbr  'git branch --remote'
alias gbs  'git bisect'
alias gbsb 'git bisect bad'
alias gbsg 'git bisect good'
alias gbsr 'git bisect reset'
alias gbss 'git bisect start'

alias gc        'git commit -v'
alias gc!       'git commit -v --amend'
alias gca       'git commit -v -a'
alias gca!      'git commit -v -a --amend'
alias gcan!     'git commit -v -a -s --no-edit --amend'
alias gcam      'git commit -a -m'
alias gcb       'git checkout -b'
alias gcf       'git config --list'
alias gcl       'git clone --recursive'
alias gclean    'git clean -fd'
alias gpristine 'git reset --hard; and git clean -dfx'
alias gcm       'git checkout master'
alias gcmsg     'git commit -m'
alias gco       'git checkout'
alias gcount    'git shortlog -sn'
alias gcp       'git cherry-pick'
alias gcs       'git commit -S'

alias gd   'git diff'
alias gdc  'git diff --cached'
alias gdct 'git describe --tags `git rev-list --tags --max-count=1`'
alias gdt  'git diff-tree --no-commit-id --name-only -r'
alias gdw  'git diff --word-diff'

alias gf  'git fetch'
alias gfa 'git fetch --all --prune'
alias gfo 'git fetch origin'

alias ggpull 'git_pull_and_prune'
alias ggpush  'git push origin (git_current_branch)'
alias ggpush! 'git push --force-with-lease origin (git_current_branch)'

alias gl 'git pull'
alias glg   'git log --stat --color'
alias glgp  'git log --stat --color -p'
alias glgg  'git log --graph --color'
alias glgga 'git log --graph --decorate --all'
alias glgm  'git log --graph --max-count=10'
alias glo   'git log --oneline --decorate --color'
alias glol  "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glola "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
alias glog  'git log --oneline --decorate --color --graph'

alias gm 'git merge'
#
alias gp    'git push'
alias gpd   'git push --dry-run'
alias gpoat 'git push origin --all; and git push origin --tags'
alias gpu   'git push upstream'
alias gpv   'git push -v'

alias gr  'git remote'
alias gra 'git remote add'
alias grb  'git rebase'
alias grba 'git rebase --abort'
alias grbc 'git rebase --continue'
alias grbi 'git rebase -i'
alias grbm 'git rebase master'
alias grbs 'git rebase --skip'
alias gre 'git review'
alias grh  'git reset HEAD'
alias grhh 'git reset HEAD --hard'
alias grmv 'git remote rename'
alias grrm 'git remote remove'
alias grset 'git remote set-url'
alias gru 'git reset --'
alias grup 'git remote update'
alias grv 'git remote -v'

alias gsb 'git status -sb'
alias gsi 'git submodule init'
alias gsh  'git show'
alias gsps 'git show --pretty=short --show-signature'
alias gss 'git status -s'
alias gst 'git status'
alias gsta  'git stash'
alias gstaa 'git stash apply'
alias gstd  'git stash drop'
alias gstl  'git stash list'
alias gstp  'git stash pop'
alias gsts  'git stash show --text'
alias gsu 'git submodule update'

alias gts 'git tag -s'
alias gtv 'git tag | sort -V'

alias gfx 'git fixup'

alias lg 'git fzf show'
