#!/usr/bin/env zsh

source "$HOME/.config/zsh/defer/_homebrew.zsh"
source "$HOME/.bin/_set_browser"

export LANG="ja_JP.UTF-8"
url=$(osascript -e "tell application \"$BROWSER\" to get URL of active tab of front window")
title=$(osascript -e "tell application \"$BROWSER\" to get title of active tab of front window")
trimmedTitle=$(echo "$title" | sed -e 's/\([^-:·|｜]*\s\?[-:·|｜]\s\?[^-:·|｜]*\)\s\?.*$/\1/')
test "$trimmedTitle" = '' && trimmedTitle="$title"
# 末尾スペースを削除
trimmedTitle="${trimmedTitle% }"
