- include: yum_settings.yml
  tags: yum_settings
- include: yum_update.yml
  tags: yum_update
- include: basic_tools.yml
  tags: basic_tools
- include: zplug.yml
  tags: zplug

- name: check libevent
  shell: ldconfig -p | grep '/usr/lib64/libevent-2.0.so.5'
  register: libevent
  failed_when:  libevent.rc not in [0, 1]
  changed_when: libevent.rc not in [0, 1]
  tags: libevent
- include: libevent.yml
  when: libevent|failed
  tags: libevent

- name: check tmux
  shell: PATH=$PATH:{{ bin_dir }} type -a tmux
  register: tmux
  failed_when:  tmux.rc not in [0, 1]
  changed_when: tmux.rc not in [0, 1]
  tags: tmux
- include: tmux.yml
  when: tmux|failed
  tags: tmux

- name: check fzf
  stat: path={{ home_dir }}/.fzf
  register: fzf
  tags: fzf
- include: fzf.yml
  when: fzf.stat.exists == False
  tags: fzf

- name: check peco
  stat: path={{ bin_dir }}/peco
  register: peco
  tags: peco
- include: peco.yml
  when: peco.stat.exists == False
  tags: peco

- name: check direnv
  stat: path={{ bin_dir }}/direnv
  register: direnv
  tags: direnv
- include: direnv.yml
  when: direnv.stat.exists == False
  tags: direnv

- name: check pt
  stat: path={{ bin_dir }}/pt
  register: pt
  tags: pt
- include: pt.yml
  when: pt.stat.exists == False
  tags: pt

- name: check ruby version
  stat: path={{ home_dir }}/.anyenv/envs/rbenv
  register: rbenv_dir
  tags: rbenv
- include: rbenv.yml
  when: rbenv_dir.stat.exists == False
  tags: rbenv

- name: check vim
  shell: PATH=$PATH:{{ bin_dir }} type -a vim && vim --version | grep 'VIM - Vi IMproved {{ vim_version }}'
  register: vim
  failed_when:  vim.rc not in [0, 1]
  changed_when: vim.rc not in [0, 1]
  tags: vim
- include: vim.yml
  when: vim|failed
  tags: vim

- name: check mysql version
  shell: mysql --version | sed -e 's/.*Distrib \([0-9.]\+\), .\+/\1/'
  register: installed_mysql_version
  tags: mysql
- name: check mysql
  shell: PATH=$PATH:{{ bin_dir }} type -a mysql
  register: mysql
  failed_when:  mysql.rc not in [0, 1]
  changed_when: mysql.rc not in [0, 1]
  tags: mysql
- include: mysql.yml
  when: mysql|failed or installed_mysql_version.stdout | version_compare(mysql_version, '<')
  tags: mysql
