#!/usr/bin/env zsh

if [ ! -r "$AGE_RECIPIENT" ]; then
  exit 1
else
  if [ -z "$i" ]; then
    rage --encrypt -o - -R $AGE_RECIPIENT -a
  else
    rage --encrypt -o - -R $AGE_RECIPIENT -a "$1"
  fi
fi
