#!/usr/bin/env zsh

if [ -z "$AGE_RECIPIENT" ]; then
  exit 1
else
  if [ -z "$AGE_IDENTITY" ]; then
    rage --encrypt -r $AGE_RECIPIENT -a
  else
    rage --encrypt -r $AGE_RECIPIENT -a "$1"
  fi
fi
