#!/usr/bin/env zsh

identifier="$(defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | awk -F'"' '/http;/{print window[(NR)-1]}{window[NR]=$2}')"
case "$identifier" in
"net.kassett.finicky")
  BROWSER="Vivaldi"
  ;;
"com.vivaldi.vivaldi")
  BROWSER="Vivaldi"
  ;;
"com.microsoft.edgemac")
  BROWSER="Microsoft Edge"
  ;;
"com.google.chrome")
  BROWSER="Google Chrome"
  ;;
*)
  BROWSER="Safari"
  ;;
esac
export BROWSER
