#!/usr/bin/env zsh

aws-login() {
  local profile=$(aws-vault list --profiles | fzf +m)

  if test -n "$profile"; then
    local url=$(aws-vault login $profile --stdout)
    echo "aws-vault login $profile"
    open $url
  else
    echo 'usage: aws-login <profile>'
  fi
}
aws-login
