#!/usr/bin/env zsh

set -euo pipefail

() {
  : ${BOOKMARKS_DIR:=$SCRAPBOOK_DIR/bookmarks}
  cd $BOOKMARKS_DIR
  rg_prefix='rg --column --line-number --no-heading --color=always --smart-case'
  selected=$(fzf --ansi --reverse --extended --multi --cycle --bind=ctrl-u:page-up,ctrl-d:page-down,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-g:toggle-all,ctrl-/:deselect-all,ctrl-q:deselect-all \
      -d: --disabled \
      --bind "start:reload:$rg_prefix ''" \
      --bind "change:reload:$rg_prefix {q} || true" \
      --preview="bat --color=always '{1}'" \
      --preview-window='down:30%:+{2}-10' | cut -d: -f1)

  test -z "$selected" && return

  for f in $(echo $selected); do
    open $(head -n1 $(echo "$f" | cut -d: -f1) | sed -e 's|^# \[.*\](\(.*\)).*|\1|')
  done
}
