#!/usr/bin/osascript

tell application "Ghostty"
  activate
  tell application "System Events"
    keystroke "p" using {command down, control down}
    delay 0.05
    keystroke "b"
    keystroke return
  end tell
end tell
