#!/usr/bin/env zsh

set -euo pipefail

() {
  echo -ne "\033]2;Bookmark Searcher\007"

  : ${BOOKMARKS_DIR:=$SCRAPBOOK_DIR/bookmarks}
  cd "$BOOKMARKS_DIR"

  suffix='(toggle: <C-t>  open: <C-o>)'
  state_file=$(mktemp)
  echo 'filtered' > $state_file

  and_search=$(mktemp)
  cat > $and_search <<'EOF'
#!/usr/bin/env zsh

mode=$1
shift
words=(${=@})

if [[ $mode == 'all' ]]; then
  cmd="rg -il ''"
else
  cmd="rg --files-without-match '#archived'"
fi

for word in $words; do
  [[ -z $word ]] && continue
  cmd="$cmd | xargs rg -il '$word'"
done

eval $cmd
EOF
  chmod +x $and_search

  preview=$(mktemp)
  cat > $preview <<'EOF'
#!/usr/bin/env zsh

file=$1
shift
words=(${=*})

[[ -z $file ]] && exit

cmd="cat '$file'"
for word in $words; do
  [[ -z $word ]] && continue
  cmd="$cmd | rg --passthru --ignore-case -N --color=always '$word'"
done

eval $cmd
EOF
  chmod +x $preview

  FZF_DEFAULT_COMMAND="$and_search filtered" \
    fzf +m --sort --ansi \
      --bind "change:reload:$and_search \$(cat $state_file) {q}" \
      --bind "enter:execute-silent:open \"\$(head -n1 {1} | sed -e 's|^# \[.*\](\(.*\)).*|\1|')\"" \
      --bind "ctrl-o:execute-silent:open 'obsidian://open?path=$BOOKMARKS_DIR/{1}'" \
      --bind "ctrl-t:execute-silent([[ \$(cat $state_file) == 'filtered' ]] && echo 'all' > $state_file || echo 'filtered' > $state_file)+transform:[[ \$(cat $state_file) == 'all' ]] \
          && echo \"reload($and_search all {q})+change-border-label('🌐 全記事 $suffix')\" \
          || echo \"reload($and_search filtered {q})+change-border-label('📌 Pickup $suffix')\"" \
      --bind ctrl-u:page-up,ctrl-d:page-down,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-g:toggle-all,ctrl-/:deselect-all,ctrl-q:deselect-all \
      --border-label="📌 Pickup $suffix" \
      --border=rounded \
      --phony -q "" \
      --preview="$preview {} {q}" \
      --preview-window="bottom,80%,wrap"

  rm -f $state_file $and_search $preview
}
