#!/usr/bin/env zsh

set -euo pipefail

() {
  : ${BOOKMARKS_DIR:=$SCRAPBOOK_DIR/bookmarks}
  cd $BOOKMARKS_DIR
  rg_prefix='rg --files-with-matches'
  selected="$(
    FZF_DEFAULT_COMMAND="$rg_prefix ''" \
      fzf --sort --preview="[[ ! -z {} ]] && rg --pretty --ignore-case -N --context 5 {q} {}" \
        --phony -q "" \
        --bind "change:reload:$rg_prefix {q}" \
        --preview-window="90%:wrap"
  )"

  test -z "$selected" && return

  for f in $(echo $selected); do
    open $(head -n1 $(echo "$f" | cut -d: -f1) | sed -e 's|^# \[.*\](\(.*\)).*|\1|')
  done
}
