#!/usr/bin/env zsh

bt() {
  installed blueutil || return 1
  installed fzf || return 1

  local op=$(echo -e "connect\ndisconnect" | fzf +m)
  test -z "$op" && return 0
  if [ "$op" = "connect" ]; then
    local selected_mac=$(blueutil --paired --format json | jq -r '.[] | [.address, .name] | join(" ")' | fzf +m --with-nth=2.. | cut -d' ' -f1)
  else
    local selected_mac=$(blueutil --connected --format json | jq -r '.[] | [.address, .name] | join(" ")' | fzf +m --with-nth=2.. | cut -d' ' -f1)
  fi
  test -z "$selected_mac" && return 0
  blueutil --$op $selected_mac
}
bt
