#!/usr/bin/env zsh

() {
  local issue_id=${1:-$(git issue-id)}
  if test -n "$issue_id"; then
    git log --color=always --graph --grep $issue_id \
        --format="%C(auto)%h%d %s %C(blue)%cr %C(green)%cN" | \
        fzf --tac --no-sort --tiebreak=index +m \
        --preview 'echo {} | rg -o \[a-f0-9\]\{7\} | head -1 | xargs -I % sh -c "git show --color=always %"' \
        --bind "ctrl-y:execute-silent: (echo {} | rg -o \[a-f0-9\]\{7\} | head -1 | tr -d '\n' | pbcopy)" \
        --bind "ctrl-m:execute: (echo {} | rg -o \[a-f0-9\]\{7\} | head -1 | xargs -I % sh -c 'git show --color=always %')"
  else
    commit_hash=$(git log --color=always --format="%C(auto)%h%d %s %C(blue)%cr %C(green)%cN" | fzf --no-sort --tiebreak=index +m --preview 'git show --color=always {1}' --bind "ctrl-y:execute-silent: (printf {1} | pbcopy)" | rg -o \[a-f0-9\]\{7\})
    test -z "$commit_hash" && return

    num=$(git log --pretty="%h" | rg -n "$commit_hash" | cut -d : -f 1)
    git log --color=always --reverse -$num \
        --format="%C(auto)%h%d %s %C(blue)%cr %C(green)%cN" | \
        fzf --no-sort --tiebreak=index +m \
        --preview 'git show --color=always {1}' \
        --bind "ctrl-y:execute-silent: (printf {1} | pbcopy)" \
        --bind "ctrl-m:execute: (echo {1} | xargs -I % sh -c 'git show --color=always %')"
  fi
} "$1"
