#!/usr/bin/env zsh

BOOKMARKS_PATH="$SCRAPBOOK_DIR/bookmarks.md"
BOOKMARK="$(cat "$BOOKMARKS_PATH" | sed -n 's|^\[\(.*\)\](\(.*\))|\1\t \2|p' | fzf --cycle --reverse +m)"
test "$BOOKMARK" != "" && open "${BOOKMARK##* }"
