#!/usr/bin/env zsh

pc() {
  PREFIX="${PASSAGE_DIR:-$HOME/.passage/store}"
  name="$(find "$PREFIX" -type f -name '*.age' | \
    sed -e "s|$PREFIX/||" -e 's|\.age$||' | \
    fzf +m)"
  if [ "$name" != "" ]; then
    passage --clip "$name"
  fi
}
pc
