#!/usr/bin/env zsh

# .config/nvim/lua/misc/todo.lua で使用するために `bin` 配下に置く
scrapbook_path() {
  : "${SCRAPBOOK_DIR:=$HOME/.scrapbook}"
  local file_path="$SCRAPBOOK_DIR"
  test "$1" = '' || file_path+="/$1"
  local dir_path=$(dirname $file_path)
  test -d "$dir_path" || mkdir -p "$dir_path"
  echo "$file_path"
}
scrapbook_path "$1"
