#!/usr/bin/env zsh

SELECTED_TAB_ID=$(wezterm cli list --format json | jq -rc ".[] | if .pane_id != $WEZTERM_PANE then [.tab_id, .title, (.cwd | gsub(\"file://$HOME/\"; \"\"))] else empty end | join(\" \")" | fzf +m --with-nth 2,3 | cut -d " " -f 1)
wezterm cli activate-tab --tab-index $1
wezterm cli activate-tab --tab-id $SELECTED_TAB_ID
