#!/usr/bin/env zsh

wezterm cli list --format json | jq -rc ".[] | [.tab_id, .title, (.cwd | gsub(\"file://$HOME/\"; \"\"))] | join(\" \")" | fzf +m --with-nth 2,3 | cut -d " " -f 1 | xargs -I % wezterm cli activate-tab --tab-id %
