# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = ENV.fetch('VAGRANT_MEMORY', 1024)
    vb.cpus   = ENV.fetch('VAGRANT_CPUS',   2)
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y git

    echo 'alias vim=vi' >> /home/vagrant/.bashrc
    echo 'git clone https://github.com/masa0x80/dotfiles.git $HOME/.dotfiles' > /home/vagrant/install
    echo 'cd $HOME/.dotfiles' >> /home/vagrant/install
    echo 'make deploy'        >> /home/vagrant/install
    echo 'make init'          >> /home/vagrant/install
    chown vagrant: /home/vagrant/install
  SHELL
end
