#!/bin/zsh

bt() {
  installed BluetoothConnector || return 1
  installed fzf || return 1

  local op=$(echo -e "connect\ndisconnect" | fzf +m)
  test -z "$op" && return 0
  local selected=$(BluetoothConnector 2>&1 | grep -o '.* - .*' | fzf +m --with-nth=3..)
  test -z "$selected" && return 0
  local mac_addr=$(echo $selected | cut -d ' ' -f1)

  BluetoothConnector --$op $mac_addr --notify
}
