#!/bin/zsh

pc() {
  local pass_name="$(fd . $PASSWORD_STORE_DIR -e gpg -x echo '{.}' | grep -oP "(?<=\\$PASSWORD_STORE_DIR/).*" | fzf --query="$@")"
  [ -z "$pass_name" ] && return 1
  pass -c $pass_name
}
