#!/bin/zsh

re() {
  local option="$(echo -e "--staged\n--worktree" | fzf +m --query="$@")"
  git status -s -uno | fzf --preview 'git diff {-1}' --prompt="\$ git restore $option (git status -s -uno)> " | cut -c4- | xargs -I% git restore $option %
}
