#!/bin/zsh

update-casks() {
  installed brew || return 1
  installed fzf || return 1

  packages=$(brew list --cask | fzf --query "$*")
  if test -n "$packages"; then
      brew update
  fi

  for pkg in $packages; do
      echo Update $pkg
      app_dir=${HOMEBREW_PREFIX}/Caskroom/$pkg
      latest_version=$(brew info $pkg | grep "$pkg:" | cut -d ' ' -f 2)
      if ! test -d $app_dir/$latest_version; then
          brew reinstall $pkg
      else
          echo -e "INFO: already updated"
      fi

      if test -n "$packages"; then
          brew cleanup
      fi
  done
}
