#!/bin/zsh

scrapbook_dir() {
  : "${SCRAPBOOK_DIR:=$HOME/.scrapbook}"
  local dir=''
  test "$1" = '' || dir="$1/"
  local dir_path="$SCRAPBOOK_DIR/$dir"
  test -d "$dir_path" || mkdir -p "$dir_path"
  # NOTE: パスにスペースが含まれる場合に備えて `:q` をつけてエスケープする
  echo "$dir_path:q"
}
