#!/bin/sh

if [ -z "$2" ]; then
  mv "$1" "$1".tmp
  ISSUE_ID=$(git issue-id)
  if test -n "$ISSUE_ID"; then
    echo '' >"$1"
    echo '' >>"$1"
    if echo "$ISSUE_ID" | grep -q '-'; then
      echo "$ISSUE_ID" >>"$1"
    else
      echo "ref. #$ISSUE_ID" >>"$1"
    fi
  fi
  cat "$1.tmp" >>"$1"
fi
