include_cookbook 'dev_tools'

include_cookbook 'anyenv'
include_cookbook 'docker'
include_cookbook 'fish'
include_cookbook 'jq'
include_cookbook 'git'
include_cookbook 'golang'
include_cookbook 'mysql'
include_cookbook 'neovim'
include_cookbook 'pyenv'
include_cookbook 'redis'
include_cookbook 'rbenv'
include_cookbook 'tmux'
