[tools]
# https://github.com/99designs/aws-vault/tags
aws-vault = "7.2.0"
# https://github.com/getsops/sops/tags
sops = "3.9.2"
# https://github.com/neovim/neovim/releases
neovim = "0.10.4"

# https://go.dev/dl/
go = "1.23.4"

# https://github.com/corretto/corretto-21/tags
java = "corretto-21.0.4.7.1"
# https://gradle.org/install/
gradle = "8.11.1"
# https://groovy.apache.org/download.html
groovy = "4.0.24"

# https://nodejs.org/en/download
node = "23.4.0"
# https://github.com/denoland/deno/tags
deno = "2.1.4"

# https://www.python.org/downloads/
python = "3.13.1"

# https://www.ruby-lang.org/en/downloads/releases/
ruby = "3.3.6"

# https://github.com/rust-lang/rust/tags
rust = "1.83.0"

# https://github.com/hashicorp/terraform/tags
terraform = "1.10.2"
# https://github.com/terraform-docs/terraform-docs/tags
terraform-docs = "0.19.0"

usage = "latest"
