abbrevs:
  - name: "tail -f"
    abbr: tailf
    snippet: "tail -f"
  - name: "diff -u"
    abbr: diff
    snippet: "diff -u"
  - name: "watch -n 0.5"
    abbr: watch
    snippet: "watch -n 0.5"
  - name: "mkdir -p"
    abbr: md
    snippet: "mkdir -p"

  - name: "git add"
    abbr: ga
    snippet: "git add"
  - name: "git add --all"
    abbr: gaa
    snippet: "git add --all"
  - name: "git branch"
    abbr: gb
    snippet: "git branch"
  - name: "git branch -a"
    abbr: gba
    snippet: "git branch -a"
  - name: "git branch --remote"
    abbr: gbr
    snippet: "git branch --remote"
  - name: "git branch -u origin/$(git branch --show-current) $(git branch --show-current)"
    abbr: gbu
    snippet: "git branch -u origin/$(git branch --show-current) $(git branch --show-current)"
    evaluate: true
  - name: "git commit"
    abbr: gc
    snippet: "git commit"
  - name: "git commit --amend"
    abbr: gc!
    snippet: "git commit --amend"
  - name: "git checkout"
    abbr: gco
    snippet: "git checkout"
  - name: "git diff"
    abbr: gd
    snippet: "git diff"
  - name: "git diff --staged"
    abbr: gds
    snippet: "git diff --staged"
  - name: "git fetch"
    abbr: gf
    snippet: "git fetch"
  - name: "git fixup"
    abbr: gfx
    snippet: "git fixup"
  - name: "git fzf show"
    abbr: lg
    snippet: "git fzf show"
  - name: "git log --stat --color"
    abbr: glg
    snippet: "git log --stat --color"
  - name: "git log --stat --color -p"
    abbr: glgp
    snippet: "git log --stat --color -p"
  - name: "git log --oneline --color --graph"
    abbr: glog
    snippet: "git log --oneline --color --graph"
  - name: "git merge --no-ff"
    abbr: gm
    snippet: "git merge --no-ff"
  - name: "git push"
    abbr: gp
    snippet: "git push"
  - name: "git pull && git delete-merged-branches"
    abbr: gpull
    snippet: "git pull && git delete-merged-branches"
  - name: "git push"
    abbr: gpush
    snippet: "git push"
  - name: "git push --force-with-lease"
    abbr: gpush!
    snippet: "git push --force-with-lease"
  - name: "git rebase"
    abbr: grb
    snippet: "git rebase"
  - name: "git rebase $(git default-branch)"
    abbr: grm
    snippet: "git rebase $(git default-branch)"
    evaluate: true
  - name: "git rebase --abort"
    abbr: gra
    snippet: "git rebase --abort"
  - name: "git rebase --continue"
    abbr: grc
    snippet: "git rebase --continue"
  - name: "git rebase -i $(git fzf)"
    abbr: gri
    snippet: "git rebase -i $(git fzf)"
  - name: "git rebase --skip"
    abbr: grs
    snippet: "git rebase --skip"
  - name: "git show"
    abbr: gsh
    snippet: "git show"
  - name: "git status -sb"
    abbr: gst
    snippet: "git status -sb"
  - name: "git tag -s"
    abbr: gts
    snippet: "git tag -s"
  - name: "git worktree"
    abbr: gwt
    snippet: "git worktree"
  - name: "git switch $(git default-branch)"
    abbr: M
    snippet: "git switch $(git default-branch)"
    evaluate: true
  - name: "git switch -c"
    abbr: br
    snippet: "git switch -c"
  - name: "git review"
    abbr: R
    snippet: "git review"
  - name: "git review"
    abbr: review
    snippet: "git review"
  - name: "lazygit"
    abbr: LG
    snippet: "lazygit"

  - name: "vagrant destroy -f"
    abbr: vdf
    snippet: "vagrant destroy -f"
  - name: "vagrant global-status"
    abbr: vst
    snippet: "vagrant global-status"

  - name: "rails c"
    abbr: c
    snippet: "rails c"
  - name: "rails s -p $RAILS_SERVER_PORT"
    abbr: s
    snippet: "rails s -p $RAILS_SERVER_PORT"
    evaluate: true
  - name: "rails db"
    abbr: db
    snippet: "rails db"
  - name: "rails routes"
    abbr: rr
    snippet: "rails routes"
  - name: "spring stop"
    abbr: ss
    snippet: "spring stop"
  - name: "bundle exec"
    abbr: be

    snippet: "bundle exec"
  - name: "bundle config set --local path vendor/bundle; bundle config set --local bin vendor/bin; bundle config set --local cache_all_platforms true; bundle install"
    abbr: bi
    snippet: "bundle config set --local path vendor/bundle; bundle config set --local bin vendor/bin; bundle config set --local cache_all_platforms true; bundle install"
  - name: "bundle config set --local path vendor/bundle; bundle config set --local bin vendor/bin; bundle config set --local cache_all_platforms true; bundle install --local"
    abbr: bil
    snippet: "bundle config set --local path vendor/bundle; bundle config set --local bin vendor/bin; bundle config set --local cache_all_platforms true; bundle install --local"

  - name: "solargraph download-core; solargraph bundle; solargraph config"
    abbr: solargraph_init
    snippet: "solargraph download-core; solargraph bundle; solargraph config"

  - name: "dc up -d"
    abbr: dcu
    snippet: "dc up -d"
  - name: "dc down"
    abbr: dcd
    snippet: "dc down"

  - name: "direnv allow"
    abbr: da
    snippet: "direnv allow"

  - name: "aws-vault exec $AWS_PROFILE --"
    abbr: A
    snippet: "aws-vault exec $AWS_PROFILE --"
    evaluate: true

  - name: "ghq get"
    abbr: Get
    snippet: "ghq get"

  - name: "| tee >(pbcopy)"
    abbr: C
    snippet: "| tee >(pbcopy)"
    global: true
  - name: "| fzf"
    abbr: F
    snippet: "| fzf"
    global: true
    if: (( ${+commands[fzf]} ))
  - name: "| rg"
    abbr: G
    snippet: "| rg"
    if: (( ${+commands[rg]} ))
    global: true
  - name: "| head"
    abbr: H
    snippet: "| head"
    global: true
  - name: "| tail"
    abbr: T
    snippet: "| tail"
    global: true
  - name: "| bat"
    abbr: L
    snippet: "| bat"
    if: (( ${+commands[bat]} ))
    global: true
  - name: "| jq"
    abbr: J
    snippet: "| jq ."
    if: (( ${+commands[jq]} ))
    global: true
  - name: ">/dev/null 2>&1"
    abbr: N
    snippet: ">/dev/null 2>&1"
    global: true
  - name: ">/dev/null"
    abbr: N1
    snippet: ">/dev/null"
    global: true
  - name: "2>/dev/null"
    abbr: N2
    snippet: "2>/dev/null"
    global: true

  - name: '$(git status -s | fzf --query="$@" | awk "{print \$2}")'
    abbr: GST
    snippet: '$(git status -s | fzf --query="$@" | awk "{print \$2}")'
    global: true
  - name: "$(git fzf)"
    abbr: GH
    snippet: "$(git fzf)"
    global: true

  - name: "mycli"
    abbr: mysql
    snippet: "mycli"
    if: (( ${+commands[mycli]} ))
  - name: "pgcli"
    abbr: psql
    snippet: "pgcli"
    if: (( ${+commands[pgcli]} ))
  - name: "g"
    abbr: g
    snippet: "rg --hidden"
    if: (( ${+commands[rg]} ))
  - name: "bat"
    abbr: cat
    snippet: "bat"
    if: (( ${+commands[bat]} ))

  - name: "ls -a"
    abbr: l
    snippet: "ls -a"
    if: (( ${+commands[eza]} ))
  - name: "ls -l --git"
    abbr: ll
    snippet: "ls -l --git"
    if: (( ${+commands[eza]} ))
  - name: "ls -la --git"
    abbr: la
    snippet: "ls -la --git"
    if: (( ${+commands[eza]} ))
  - name: "eza -T --icons"
    abbr: tree
    snippet: "eza -T --icons"
    if: (( ${+commands[eza]} ))

  - name: "rm"
    abbr: rm
    snippet: "rip"
    if: (( ${+commands[rip]} ))
  - name: "rmdir"
    abbr: rd
    snippet: "rip"
    if: (( ${+commands[rip]} ))
  - name: "rip"
    abbr: rf
    snippet: "rip"
    if: (( ${+commands[rip]} ))

  - name: "silicon --to-clipboard --from-clipboard -l ts"
    abbr: Si
    snippet: "silicon --to-clipboard --from-clipboard -l ts"
    if: (( ${+commands[silicon]} ))
  - name: 'silicon --to-clipboard --from-clipboard -l ts --highlight-lines "1;2-3"'
    abbr: SI
    snippet: 'silicon --to-clipboard --from-clipboard -l ts --highlight-lines "1;2-3"'
    if: (( ${+commands[silicon]} ))

  - name: "vi ~/.ssh/config"
    abbr: ssh_config
    snippet: "vi ~/.ssh/config"
    if: test -e "$HOME/.ssh/config"
  - name: "vi ~/.ssh/config"
    abbr: sconfig
    snippet: "vi ~/.ssh/config"
    if: test -e "$HOME/.ssh/config"
  - name: "vi ~/.ssh/config"
    abbr: sconf
    snippet: "vi ~/.ssh/config"
    if: test -e "$HOME/.ssh/config"

  - name: "test"
    abbr: t
    snippet: "rspec"
    if: (( ${+commands[rspec]} ))
  - name: "test"
    abbr: t
    snippet: "npm run test"
    if: test -e package.json
