# vim: ft=ruby
tap "homebrew/core"
tap "homebrew/services"

brew "autoconf"
brew "automake"
brew "boost"
brew "coreutils"
brew "curl"
brew "gdbm"
brew "gettext"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "less"
brew "llvm"
brew "libgit2"
brew "libsodium"
brew "openssl"

brew "bluetoothconnector"
brew "fzf"
brew "gibo"
brew "git"
brew "jo"
brew "jq"
brew "lsof"
brew "mas"
brew "tldr"
brew "pass"
brew "rsync"
brew "watch"

# NOTE diagrams requires installing graphviz
# ref. https://diagrams.mingrammer.com/docs/getting-started/installation
brew "graphviz"

brew "asdf"
brew "direnv"

brew "zsh"

brew "navi"

brew "mysql"
brew "postgresql"
brew "redis"

brew "neovim"

brew "awscli"

brew "bat"
brew "dog"
brew "eza"
brew "fd"
brew "git-delta"
brew "ripgrep"
brew "sd"
brew "silicon"
brew "grex"

brew "hub"
brew "gh"
brew "ghq"

brew "csvq"

brew "lazydocker"
brew "dive"

brew "pinentry-mac"

brew "httpie"
brew "yq"

brew "protobuf"

tap "arkweid/lefthook"
brew "lefthook"

brew "markdownlint-cli"

# for telescope / telekasten
brew "catimg"

tap "ryooooooga/tap"
brew "zabrze"

tap "daipeihust/tap"
brew "im-select"
