#!/bin/bash

_asdf_install() {
  . "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"

  NAME="$1"
  VERSION=$(sed -n "s|^\s*$NAME \(.*\)|\1|p" "$HOME/.tool-versions")

  asdf plugin add "$NAME" "$2"
  asdf install "$NAME" "$VERSION"
}
_asdf_install "$1" "$2"
