#!/bin/zsh

filename="Catppuccin%20Mocha.tmTheme"
if [ ! -f ".config/bat/themes/$filename" ]; then
  cd "$(bat --config-dir)/themes"
  curl -s -O "https://github.com/catppuccin/bat/raw/main/themes/$filename"
fi
