#!/bin/bash

# NOTE: NONINTERACTIVE=1
#       Suppress "Press RETURN to continue or any other key to abort"
if ! type brew >/dev/null; then
  HOMEBREW_PREFIX='/opt/homebrew' NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
export HOMEBREW_NO_ANALYTICS=1
brew update
brew upgrade
brew tap homebrew/bundle
