#!/bin/bash

# Hide Dock automatically
defaults write com.apple.dock autohide -bool true

# Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Dock animation
defaults write com.apple.dock autohide-time-modifier -float 0.7

# Fix battery indicator
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Change the directory that saves screen shots
dir=$HOME/Pictures/ScreenShots/
mkdir -p "$dir"
defaults write com.apple.screencapture location -string "$dir"
defaults write com.apple.screencapture name -string 'ScreenShot'
defaults write com.apple.screencapture show-thumbnail -bool false

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show file ext
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show directory first
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Do not make .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Key Repeat
# Set delay until key repeat (15 * n [ms])
defaults write NSGlobalDomain InitialKeyRepeat -int 12
# Set key repeat speed (15 * n [ms])
defaults write NSGlobalDomain KeyRepeat -int 1

# Fix tap behavior
defaults write -g com.apple.mouse.tapBehavior -int 1

# Disable spotlight
# mdutil -s / | grep enabled && sudo mdutil -a -i off /

# VSCode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Keyboard Shortcuts
defaults write com.microsoft.Outlook NSUserKeyEquivalents -dict-add "Clear Formatting" -string "@l"

killall Dock
killall Finder
killall SystemUIServer
