#!/bin/bash

# Hide Dock automatically
defaults write com.apple.dock autohide -bool true

# Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Dock animation
defaults write com.apple.dock autohide-time-modifier -float 0.7

# Fix battery indicator
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Changer OS language
defaults write -g AppleLanguages -array en ja

# Change the directory that saves screen shots
dir=${SS_DIR:-$HOME/Pictures/ScreenShots/}
mkdir -p "$dir"
defaults write com.apple.screencapture location -string "$dir"
defaults write com.apple.screencapture name -string 'ScreenShot'
defaults write com.apple.screencapture show-thumbnail -bool false

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show file ext
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show directory first
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Do not make .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Key Repeat
# Set delay until key repeat (15 * n [ms])
defaults write NSGlobalDomain InitialKeyRepeat -int 12
# Set key repeat speed (15 * n [ms])
defaults write NSGlobalDomain KeyRepeat -int 1

# Fix tap behavior
defaults write -g com.apple.mouse.tapBehavior -int 1

# Disable spotlight
# mdutil -s / | grep enabled && sudo mdutil -a -i off /

# VSCode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Keyboard Shortcuts
defaults write com.microsoft.Outlook NSUserKeyEquivalents -dict-add "Clear Formatting" -string "@l"

# Disable Shortcuts for spotlight
# ref. https://qiita.com/ry0f/items/f2c75f0a77b1012182d6
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 64 "<dict><key>enabled</key><false/><key>value</key><dict><key>parameters</key><array><integer>32</integer><integer>49</integer><integer>1048576</integer></array><key>type</key><string>standard</string></dict></dict>"
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 65 "<dict><key>enabled</key><false/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>49</integer><integer>1572864</integer></array><key>type</key><string>standard</string></dict></dict>"

# Change "Move focus to next window" shortcut
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 27 "<dict><key>enabled</key><true/><key>value</key><dict><key>parameters</key><array><integer>65535</integer><integer>48</integer><integer>524288</integer></array><key>type</key><string>standard</string></dict></dict>"

killall Dock
killall Finder
killall SystemUIServer
