#!/bin/zsh

tmpl_dir="$ZDOTDIR/tmpl"
zshenv_cache="$XDG_CACHE_HOME/zshenv-cache.zsh"
zshrc="$ZDOTDIR/.zshrc"

# .zshenv cache
echo -n > $zshenv_cache

# homebrew
brew shellenv >> $zshenv_cache
source $zshenv_cache

export AGE_IDENTITY="$HOME/.config/age/key.txt"
echo "export AGE_IDENTITY=$AGE_IDENTITY" >> $zshenv_cache
echo "export AGE_RECIPIENT=\"$(grep -oP '(?<=# public key: ).+(?=)' "$AGE_IDENTITY")\"" >> $zshenv_cache
echo "export PASSAGE_IDENTITIES_FILE=\"$HOME/.ssh/key\"" >> $zshenv_cache
echo "export PASSAGE_RECIPIENTS_FILE=\"$HOME/.ssh/key.pub\"" >> $zshenv_cache
echo "export PASSAGE_AGE=\"$HOMEBREW_PREFIX/bin/rage\"" >> $zshenv_cache

# Browser
identifier="$(defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | awk -F'"' '/http;/{print window[(NR)-1]}{window[NR]=$2}')"
target_browser="Safari"
case "$identifier" in
"se.johnste.finicky")
  target_browser="Vivaldi"
  ;;
"com.vivaldi.vivaldi")
  target_browser="Vivaldi"
  ;;
"com.microsoft.edgemac")
  target_browser="Microsoft Edge"
  ;;
"com.google.chrome")
  target_browser="Google Chrome"
  ;;
esac
echo "export TARGET_BROWSER=\"$target_browser\"" >> $zshenv_cache

# Generate .zshrc
echo -n > $zshrc

# misc
(( ${+commands[mise]} )) && mise activate zsh >> $zshrc
(( ${+commands[fzf]} )) && fzf --zsh >> $zshrc
(( ${+commands[direnv]} )) && direnv hook zsh >> $zshrc
(( ${+commands[starship]} )) && starship init zsh >> $zshrc

cat $tmpl_dir/init.zsh >> $zshrc

# sheldon
sheldon source >> $zshrc

for file (
  $tmpl_dir/aliases.zsh(N)
  $tmpl_dir/check-envrc-exist.zsh(N)
  $tmpl_dir/check-local-git-config.zsh(N)
  $tmpl_dir/complete-ssh-host.zsh(N)
  $tmpl_dir/completion.zsh(N)
  $tmpl_dir/dotdot.zsh(N)
  $tmpl_dir/fzf.zsh(N)
  $tmpl_dir/ghq.zsh(N)
  $tmpl_dir/git-add.zsh(N)
  $tmpl_dir/git-branch.zsh(N)
  $tmpl_dir/key-bindings.zsh(N)
  $tmpl_dir/navi.zsh(N)
  $tmpl_dir/prompt.zsh(N)
  $tmpl_dir/r.zsh(N)
) cat $file >> $zshrc

for file (
  # Load gcloud
  $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc(N)
  $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc(N)
) echo "zsh-defer source \"$file\"" >> $zshrc

# zabrze
zabrze init --bind-keys >> $zshrc

for file (
  # Load local configurations
  $HOME/.config.local/zsh/zshrc(N)
  $HOME/.zshrc.local(N)
) cat $file >> $zshrc

cat $tmpl_dir/local-bin.zsh >> $zshrc

# zcompile
for file (
  $zshenv_cache
  $zshrc
  $HOME/.zshenv(N)
  $HOME/.config.local/zsh/zshenv(N)
  $HOME/.zshenv.local(N)
) zcompile $file
