#!/bin/zsh

zshenv_cache="$XDG_CACHE_HOME/zshenv-cache.zsh"
zshrc_cache="$XDG_CACHE_HOME/zshrc-cache.zsh"

# .zshenv cache
echo -n > $zshenv_cache

# homebrew
brew shellenv >> $zshenv_cache
source $zshenv_cache

export AGE_IDENTITY="$HOME/.config/age/key.txt"
echo "export AGE_IDENTITY=$AGE_IDENTITY" >> $zshenv_cache
echo "export AGE_RECIPIENT=\"$(grep -oP '(?<=# public key: ).+(?=)' "$AGE_IDENTITY")\"" >> $zshenv_cache
echo "export PASSAGE_IDENTITIES_FILE=\"$HOME/.ssh/key\"" >> $zshenv_cache
echo "export PASSAGE_RECIPIENTS_FILE=\"$HOME/.ssh/key.pub\"" >> $zshenv_cache
echo "export PASSAGE_AGE=\"$HOMEBREW_PREFIX/bin/rage\"" >> $zshenv_cache

# Browser
identifier="$(defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | awk -F'"' '/http;/{print window[(NR)-1]}{window[NR]=$2}')"
target_browser="Safari"
case "$identifier" in
"se.johnste.finicky")
  target_browser="Vivaldi"
  ;;
"com.vivaldi.vivaldi")
  target_browser="Vivaldi"
  ;;
"com.microsoft.edgemac")
  target_browser="Microsoft Edge"
  ;;
"com.google.chrome")
  target_browser="Google Chrome"
  ;;
esac
echo "export TARGET_BROWSER=\"$target_browser\"" >> $zshenv_cache

# Generate .zshrc
echo -n > $zshrc_cache

# misc
(( ${+commands[mise]} )) && mise activate zsh >> $zshrc_cache
(( ${+commands[fzf]} )) && fzf --zsh >> $zshrc_cache
(( ${+commands[direnv]} )) && direnv hook zsh >> $zshrc_cache
(( ${+commands[starship]} )) && starship init zsh >> $zshrc_cache

# sheldon
sheldon source >> $zshrc_cache

# zabrze
zabrze init --bind-keys >> "$XDG_CACHE_HOME/zabrze-cache.zsh"

# zcompile
for file (
  $zshenv_cache
  $zshrc_cache_cache
  $HOME/.zshenv(N)
  $HOME/.zshrc(N)
  $HOME/.config.local/zsh/zshenv(N)
  $HOME/.zshenv.local(N)
) zcompile $file
