#!/usr/bin/env zsh

go install golang.org/x/tools/...@latest
go install golang.org/x/tools/cmd/gopls@latest
go install github.com/MichaelMure/mdr@latest
go install github.com/mattn/goreman@latest
go install github.com/rakyll/statik@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
