#!/usr/bin/env zsh

install() {
  go get $1
}

update() {
  go get -u -t $1
}

cmd=${1:-install}
$cmd github.com/direnv/direnv

$cmd github.com/github/hub
$cmd github.com/hashicorp/packer
$cmd github.com/jesseduffield/lazydocker

$cmd github.com/skanehira/tson
$cmd github.com/itchyny/gojq/cmd/gojq
$cmd github.com/itchyny/gojo/cmd/gojo

$cmd github.com/mattn/files
$cmd github.com/monochromegane/the_platinum_searcher/cmd/pt
$cmd github.com/peco/peco/cmd/peco
