#!/usr/bin/env zsh

install() {
  go get $1
}

install github.com/direnv/direnv

install github.com/github/hub
install github.com/hashicorp/packer
install github.com/jesseduffield/lazydocker

install github.com/skanehira/tson
install github.com/itchyny/gojq/cmd/gojq
install github.com/itchyny/gojo/cmd/gojo

install github.com/mattn/files
install github.com/monochromegane/the_platinum_searcher/cmd/pt
install github.com/peco/peco/cmd/peco
