#!/bin/bash

CURRENT_DIR=$(
  cd "$(dirname "$0")" || exit
  pwd
)
source "$CURRENT_DIR/_asdf_install" helm

helm plugin list | grep secrets || helm plugin install https://github.com/zendesk/helm-secrets
helm plugin list | grep diff || helm plugin install https://github.com/databus23/helm-diff
