#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

VERSION=$(grep -oP '(?<=nodejs ).*' $HOME/$ASDF_DEFAULT_TOOL_VERSIONS_FILENAME)

export NODEJS_CHECK_SIGNATURES=no
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs $VERSION
