#!/bin/bash

. $(brew --prefix asdf)/libexec/asdf.sh

VERSION=$(grep nodejs "$HOME/.tool-versions" | grep -o '[0-9\.]*')

export NODEJS_CHECK_SIGNATURES=no
asdf plugin-add nodejs
asdf install nodejs "$VERSION"
