#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

VERSION=$(grep -oP '(?<=nodejs ).*' $HOME/.tool-versions)

export NODEJS_CHECK_SIGNATURES=no
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs $VERSION
