#!/usr/bin/env zsh

test -d $PYENV_ROOT || anyenv install pyenv

# Pythohn 2
pyenv versions | grep -q $PYTHON2_VERSION || pyenv install $PYTHON2_VERSION

# Pythohn 3
pyenv versions | grep -q $PYTHON3_VERSION || pyenv install $PYTHON3_VERSION
pyenv versions | grep -q "* $PYTHON3_VERSION" | grep -q "* $PYTHON2_VERSION" || pyenv global $PYTHON3_VERSION $PYTHON2_VERSION

python3 -m pit install --upgrade pip

# Python tools
pip_install() {
  if python3 -m pip list | grep -i $1; then
    python3 -m pip install $1
  fi
}

pip_install neovim
pip_install awscli
pip_install diagrams
