#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

PYTHON_VERSIONS=($(grep -oP '(?<=python ).*' $HOME/.tool-versions))

asdf plugin-add python

for v in $PYTHON_VERSIONS; do
  asdf install python $v
done
