#!/bin/bash

. "$(brew --prefix asdf)/libexec/asdf.sh"

VERSION=$(sed -n 's|python \(.*\)|\1|p' "$HOME/.tool-versions")

asdf plugin-add python
asdf install python "$VERSION"
pip install --upgrade pip
