#!/bin/bash

. $(brew --prefix asdf)/libexec/asdf.sh

PYTHON_VERSIONS=$(grep python "$HOME/.tool-versions" | grep -o '[0-9\.]*')

asdf plugin-add python

for v in $PYTHON_VERSIONS; do
  asdf install python "$v"
done
pip install --upgrade pip
