#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

VERSION=$(grep -oP '(?<=ruby ).*' $HOME/$ASDF_DEFAULT_TOOL_VERSIONS_FILENAME)

asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf install ruby $VERSION
