#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

VERSION=$(grep -oP '(?<=terraform ).*' $HOME/.tool-versions)

asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
asdf install terraform $VERSION
