#!/usr/bin/env zsh

. $(brew --prefix asdf)/asdf.sh

asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
asdf install terraform $TERRAFORM_VERSION
asdf global terraform $TERRAFORM_VERSION
