#!/bin/zsh

if [ ! -d .config/tmux/plugins/catppuccin/tmux ]; then
  git clone https://github.com/catppuccin/tmux.git .config/tmux/plugins/catppuccin/tmux
fi
if [ ! -d .config/tmux/plugins/tmux-plugins/tmux-battery ]; then
  git clone https://github.com/tmux-plugins/tmux-battery.git .config/tmux/plugins/tmux-plugins/tmux-battery
fi
if [ ! -d .config/tmux/plugins/tmux-plugins/tmux-cpu ]; then
  git clone https://github.com/tmux-plugins/tmux-cpu.git .config/tmux/plugins/tmux-plugins/tmux-cpu
fi
