#!/bin/zsh

dirname=".config/tmux/plugins/catppuccin/tmux"
if [ ! -d $dirname ]; then
  git clone https://github.com/catppuccin/tmux.git $dirname
fi
dirname=".config/tmux/plugins/tmux-plugins/tmux-battery"
if [ ! -d $dirname ]; then
  git clone https://github.com/tmux-plugins/tmux-battery.git $dirname
fi
dirname=".config/tmux/plugins/tmux-plugins/tmux-cpu"
if [ ! -d $dirname ]; then
  git clone https://github.com/tmux-plugins/tmux-cpu.git $dirname
fi
