require("hop").setup({
	uppercase_labels = true,
})

local hop = require("hop")
local directions = require("hop.hint").HintDirection
vim.keymap.set("", "<Leader><Space>", function()
	hop.hint_words({})
end, { remap = true })
vim.keymap.set("", "<Leader>k", function()
	hop.hint_words({ direction = require("hop.hint").HintDirection.BEFORE_CURSOR })
end, { remap = true })
vim.keymap.set("", "<Leader>j", function()
	hop.hint_words({ direction = require("hop.hint").HintDirection.AFTER_CURSOR })
end, { remap = true })
vim.keymap.set("", "f", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, { remap = true })
vim.keymap.set("", "F", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, { remap = true })
vim.keymap.set("", "t", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, { remap = true })
vim.keymap.set("", "T", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { remap = true })
