local hop = require("hop")
hop.setup({})

local map = require("utils").map
map("", "<CR>", function()
	hop.hint_vertical()
end, {})

local directions = require("hop.hint").HintDirection
map("", "<A-f>", "f", { remap = false })
map("", "<A-F>", "F", { remap = false })
map("", "<A-t>", "t", { remap = false })
map("", "<A-T>", "T", { remap = false })
map("", "f", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, { remap = true })
map("", "F", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, { remap = true })
map("", "t", function()
	hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, { remap = true })
map("", "T", function()
	hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, { remap = true })
