---@diagnostic disable: missing-fields
require("hop").setup({})

local map = vim.keymap.set
local opts = { remap = true }
local hop = require("hop")
local direction = require("hop.hint").HintDirection
map("", "<Leader><Space>", function()
	hop.hint_words({ current_line_only = true })
end, opts)
map("", "<C-g><C-k>", function()
	hop.hint_lines({ direction = direction.BEFORE_CURSOR })
end, opts)
map("", "<C-g><C-g><C-k>", function()
	hop.hint_words({ direction = direction.BEFORE_CURSOR })
end, opts)
map("", "<C-g><C-j>", function()
	hop.hint_lines({ direction = direction.AFTER_CURSOR })
end, opts)
map("", "<C-g><C-g><C-j>", function()
	hop.hint_words({ direction = direction.AFTER_CURSOR })
end, opts)

map("", "<A-f>", function()
	hop.hint_char1({ direction = direction.AFTER_CURSOR, current_line_only = true })
end, opts)
map("", "<A-S-f>", function()
	hop.hint_char1({ direction = direction.BEFORE_CURSOR, current_line_only = true })
end, opts)
map("", "<A-t>", function()
	hop.hint_char1({ direction = direction.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, opts)
map("", "<A-S-t>", function()
	hop.hint_char1({ direction = direction.BEFORE_CURSOR, current_line_only = true, hint_offset = -1 })
end, opts)
