#!/bin/sh

APPLYPATCH_MSG=1
COMMIT_MSG=$((1<<1))
FSMONITOR_WATCHMAN=$((1<<2))
POST_UPDATE=$((1<<3))
PRE_APPLYPATCH=$((1<<4))
PRE_COMMIT=$((1<<5))
PRE_MERGE_COMMIT=$((1<<6))
PRE_PUSH=$((1<<7))
PRE_REBASE=$((1<<8))
PRE_RECEIVE=$((1<<9))
PREPARE_COMMIT=$((1<<10))
PREPARE_COMMIT_MSG=$((1<<11))
UPDATE=$((1<<12))

GIT_ROOT=$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)
HOOK_NAME=$(basename $0)
LOCAL_HOOK="$GIT_ROOT/.git/hooks/$HOOK_NAME"
if test -e $LOCAL_HOOK; then
  HOOK_FILE=$LOCAL_HOOK
fi

# $GIT_DIR/hooks 配下にhookファイルがある場合実行する
if test -n "$HOOK_FILE"; then
  sh $HOOK_FILE "$@"
fi

if test -z "$GLOBAL_GIT_HOOK"; then
  GLOBAL_GIT_HOOK=0
fi
