#!/bin/sh

source "$(dirname $0)/_hook_init"

# $GIT_DIR/hooks 配下にhookファイルがないか、$GLOBAL_GIT_HOOKフラグが立っている場合実行する
# if test -z "$HOOK_FILE" || test $(($GLOBAL_GIT_HOOK & $COMMIT_MSG)) = $COMMIT_MSG; then
# fi
