#!/bin/sh

source "$(dirname $0)/_hook_init"

# $GIT_DIR/hooks 配下にhookファイルがないか、$GLOBAL_GIT_HOOKフラグが立っている場合実行する
if test -z "$HOOK_FILE" || test $(($GLOBAL_GIT_HOOK & $PRE_PUSH)) = $PRE_PUSH; then
  PJ_ROOT=$(git rev-parse --show-cdup)

  if test -z "$DISABLE_RUBOCOP"; then
    if test -e "${PJ_ROOT}.rubocop.yml"; then
      bundle exec rubocop --parallel
      rubocop_status=$?
      if test $rubocop_status -ne 0; then
        exit $rubocop_status
      fi
    fi
  fi

  if test -z "$DISABLE_RSPEC"; then
    if test -d "${PJ_ROOT}spec/"; then
      bundle exec rspec
      rspec_status=$?
      if test $rspec_status -ne 0; then
        exit $rspec_status
      fi
    fi
  fi
fi
