#!/bin/bash

pre_push() {
  local git_root=`git rev-parse --show-cdup`

  if test "$DISABLE_RUBOCOP" = ''; then
    if test -e "${git_root}.rubocop.yml"; then
      bundle exec rubocop `git diff --staged --name-only`
      local rubocop_status=$?
      if test $rubocop_status -ne 0; then
        exit $rubocop_status
      fi
    fi
  fi

  if test "$DISABLE_RSPEC" = ''; then
    if test -d "${git_root}spec/"; then
      bundle exec rspec
      local rspec_status=$?
      if test $rspec_status -ne 0; then
        exit $rspec_status
      fi
    fi
  fi
}
pre_push
