#!/bin/sh

if [ "$2" == '' ]; then
  mv $1 $1.tmp
  ISSUE_NUMBER=`git rev-parse --abbrev-ref @ | sed -e 's/^[^0-9]*\([0-9]*\).*/\1/'`
  if [ ! -z $ISSUE_NUMBER ]; then
    echo "[#${ISSUE_NUMBER}] " > $1
  fi
  cat $1.tmp >> $1
fi
