# tap repositories and their packages
tap rcmdnk/file
brew brew-file

tap homebrew/services

tap homebrew/dupes
brew less
brew lsof
brew rsync

# Other Homebrew packages
brew autoconf
brew automake
brew boost
brew cmake
brew coreutils
brew cpulimit
brew curl
brew emojify
brew fish
brew fzf
brew gdbm
brew gettext
brew git
brew gibo
brew global --with-ctags --with-pygments
brew go
brew graphviz
brew htop
brew imagemagick
brew jq
brew jo
brew keychain
brew libevent
brew libtool
brew libyaml
brew mysql
brew oniguruma
brew openssl
brew parallel
brew pass
brew pcre
brew phantomjs
brew pkg-config
brew postgresql
brew readline
brew reattach-to-user-namespace
brew redis
brew tmux
brew tree
brew vim --with-lua --without-python
brew watch
brew wget
brew xz
brew zsh --without-etcdir
brew https://raw.githubusercontent.com/BurntSushi/ripgrep/master/pkg/brew/ripgrep.rb

tap neovim/neovim
brew neovim --HEAD

tap caskroom/cask
file $HOME/.brewfile/cask

tap argon/mas
brew mas
file $HOME/.brewfile/appstore
