[settings]
idiomatic_version_file_enable_tools = ["node"]
install_before = "7d"
paranoid = true
disable_backends = ["asdf"]

[settings.github]
use_git_credentials = true

[settings.node]
gpg_verify = false

[tools]
"aqua:aws/session-manager-plugin" = "latest"

actionlint = "latest"

awscli = "latest"
aws-sam-cli = "latest"
aws-vault = "latest"

gh = "latest"

go = "latest"

java = "latest"
gradle = "latest"
groovy = "latest"

jq = "latest"

lefthook = "latest"

# https://github.com/neovim/neovim/releases
neovim = "0.11.6"

node = "latest"
deno = "latest"

op = "latest"

python = "latest"
uv = "latest"

ruby = "latest"

rust = "latest"

sops = "latest"

terraform = "latest"
terraform-docs = "latest"

tree-sitter = "latest"
